Repository pcaversaccio/safe-tx-hashes-util, pull requests merged in 2025-03, with the labels that each got.

#14 🔒 Add Warning for Untrusted `delegatecall`s
  README.md
  safe_hashes.sh
Labels: documentation 📖, feature 💥

#17 🔒 Add Utility Function to Detect Potential Gas Token Attack
  safe_hashes.sh
Labels: feature 💥

#24 🐛 Fix Nonce Default in `--interactive` Mode
  safe_hashes.sh
Labels: bug 🐛, refactor/cleanup ♻️

#25 ✨ Add `--version` Flag
  README.md
  safe_hashes.sh
Labels: documentation 📖, feature 💥, refactor/cleanup ♻️

#26 ✨ Add Support for Nested Safes
  .github/workflows/checks.yml
  README.md
  safe_hashes.sh
Labels: documentation 📖, feature 💥, ci/cd 👷‍♂️

#27 ♻️ Update to `v2` in `safes/${address}/multisig-transactions` Endpoint
  README.md
  safe_hashes.sh
Labels: documentation 📖, refactor/cleanup ♻️

#29 ✨ Add Support for Berachain, Ink, Sonic, and Unichain
  README.md
  safe_hashes.sh
Labels: documentation 📖, feature 💥
